### ISSUE TITLE
incorrect redirection of back button 

### ISSUE THREAD

**Issue by 4bh7n4v** [Vinay-Khanagavi/Cyberbear.github.io#102]
The back button is not redirecting properly at phishing awareness after level-3 

https://github.com/user-attachments/assets/7622b037-c980-4d61-a675-91981eba7714

Please assign me this @B1N4RY-P4R45173

**Comment by B1N4RY-P4R45173** [comment]
Please wait till your previous pr gets merged we can assign a person only 1 issue till it gets closed

**Comment by Raj100** [comment]
Please assign this issue to me and add ggsoc ext label too! Thank You!😊

**Comment by B1N4RY-P4R45173** [comment]
Hello there this issue has been resolved. You can join our discord server and check the other issues
