### ISSUE TITLE
[Feature] Add Translation Tool 

### ISSUE THREAD

**Issue by Subhajit-2023-44** [Vinay-Khanagavi/Cyberbear.github.io#12]
I want to add a Translation Tool(all language) properly.

@Vinay-Khanagavi  PA please assign me this task.

![Screenshot 2024-10-14 155122](https://github.com/user-attachments/assets/2770137a-6115-4409-8024-8573982e4981)

**Comment by Vinay-Khanagavi** [comment]
Translation tool is not needed for now, but if you want to work that sure

**Comment by Subhajit-2023-44** [comment]
@Vinay-Khanagavi sir I'm interest, but sir level 1 is too low for this work, if you check other projects, they are giving level 3/2 for this.    If you don't want to give level 3 then at least add level 2. 

Thank you

**Comment by Vinay-Khanagavi** [comment]
Okay give PR

**Comment by Subhajit-2023-44** [comment]
> Okay give PR

@Vinay-Khanagavi okay sir
