### ISSUE TITLE
Add Navigation Bar to Improve Site Usability

### ISSUE THREAD

**Issue by Ankul8471** [Vinay-Khanagavi/Cyberbear.github.io#121]
Currently, the site lacks a consistent navigation bar, making it difficult for users to browse through different sections efficiently. Adding a navigation bar with links to key sections (e.g., Home, About, Services, Contact) would enhance the user experience by providing an intuitive and structured way to move through the site. The navigation bar should be responsive and adapt to different screen sizes for optimal mobile and desktop use. I propose adding this feature to improve usability and user retention.
![Screenshot 2024-10-22 002325](https://github.com/user-attachments/assets/465c03a9-c10c-424e-b1d8-a6cfcf63d3fa)

**Comment by Vinay-Khanagavi** [comment]
Currently the landing page isn't available for open-source,
please open issues on main project
