### ISSUE TITLE
Add Footer for Site Consistency and Additional Information

### ISSUE THREAD

**Issue by Ankul8471** [Vinay-Khanagavi/Cyberbear.github.io#122]
The website currently lacks a footer, which can be used to provide users with important information such as quick links, social media handles, contact details, and copyright information. A well-designed footer would improve site consistency and offer a convenient way for users to access this information across all pages. The footer should be responsive and visually integrated with the overall site design. Adding this feature will enhance both usability and the professional appearance of the website.
![Screenshot 2024-10-22 002325](https://github.com/user-attachments/assets/62aee566-b9a9-4435-90e2-418b056d1e4a)

**Comment by Vinay-Khanagavi** [comment]
Currently the landing page isn't available for open-source,
please open issues on main project
