### ISSUE TITLE
[FEATURE] Add Feedback/Rate Us section

### ISSUE THREAD

**Issue by Subhajit-2023-44** [Vinay-Khanagavi/Cyberbear.github.io#13]
I want to add a Feedback/Rate section.

@Vinay-Khanagavi  PA please assign me this task.

![Screenshot 2024-10-14 155108](https://github.com/user-attachments/assets/14ddd49b-f3be-4175-99eb-f3ad80662a3d)

**Comment by Vinay-Khanagavi** [comment]
Can you elaborate how that feedback section will look like with any examples !

**Comment by Subhajit-2023-44** [comment]
PA @Vinay-Khanagavi Feedback/Rate Us section look like -

![Screenshot 2024-10-14 164907](https://github.com/user-attachments/assets/8d6ce8f6-477b-4404-aee6-fe40a5388328)
![Screenshot 2024-10-14 164124](https://github.com/user-attachments/assets/a139b5ba-89db-4447-906f-cd4a7d63f697)
![Screenshot 2024-10-14 163525](https://github.com/user-attachments/assets/0da75fd6-189a-4817-8032-ce534e7dee2d)
![Screenshot 2024-10-14 162416](https://github.com/user-attachments/assets/30d43a8b-ea74-45ba-9791-e5911db00284)

Level 3

**Comment by Vinay-Khanagavi** [comment]
@aditichhawacharia check whether this is needed!?

**Comment by Subhajit-2023-44** [comment]
> @aditichhawacharia check whether this is needed!?

@Vinay-Khanagavi @aditichhawacharia actually almost all websites have an feedback/rate us section/page.     That is why I am giving the assign request.

I am interest..

**Comment by Subhajit-2023-44** [comment]
@Vinay-Khanagavi @aditichhawacharia

**Comment by B1N4RY-P4R45173** [comment]
@Subhajit-2023-44 I am closing this issue because we don't find the Feedback section helpful for us at the moment. @Vinay-Khanagavi we can reopen this if we need it in the future
