### ISSUE TITLE
Feature: Add Google Translate Support

### ISSUE THREAD

**Issue by jjf2009** [Vinay-Khanagavi/Cyberbear.github.io#133]
Description: Integrating Google Translate support into an application would allow users to automatically translate text between multiple languages. This feature will use Google's powerful translation API to convert input text in one language into a target language, enabling users to communicate and interact with content regardless of language barriers.

Kindly assign me this issue under gssoc-ext hacktobter and level-2

**Comment by B1N4RY-P4R45173** [comment]
We have some issues with implementing this. Can u join our discord so we can decide to use it if u have a better implementation idea

**Comment by Vinay-Khanagavi** [comment]
Sorry nope we dont
