### ISSUE TITLE
Video auto-plays without the button changing to pause

### ISSUE THREAD

**Issue by Blink-drift** [Vinay-Khanagavi/Cyberbear.github.io#144]
Problem:
The videos on some pages, start auto-playing without the play/pause button updating to pause.

Solution
There are two ways to fix this, either the videos should be stopped from auto playing or, the button needs to be updated to pause whenever the video plays.

**Comment by Blink-drift** [comment]
Can you kindly assign this issue to me?

**Comment by B1N4RY-P4R45173** [comment]
Thanks dude, actually even I saw this. But I thought this was an issue on my side and forgot about it. You can start with th pr. Updating the status of button should be a better approach. (We intend the videos to play automatically)

**Comment by B1N4RY-P4R45173** [comment]
Also yeah pls join our discord, u can ask there if u need any more clarification or if u have any other better ideas

**Comment by Blink-drift** [comment]
Alright, I will. Thank you for assigning me
