### ISSUE TITLE
Improvement of the Contact Form

### ISSUE THREAD

**Issue by vcerpasalas** [Vinay-Khanagavi/Cyberbear.github.io#145]
Hi, I would like to work on an update on the Contact form (Access CyberBear for free):

1. Adding a Short Description / Tagline for Clarity:
A one-liner description below the title that highlights CyberBear's value proposition. For example:
Get hands-on with cutting-edge cybersecurity tools designed to protect your digital life

2. Adding a Privacy Disclaimer for Reassurance:
Add a short privacy statement below the form to reassure users about the use of their data:
We respect your privacy and will only use your information to notify you about CyberBear access.

3. Add a dropdown button to select the country (with flag) and its code, followed by a field to enter the phone number.

4. Suggest an improved text for confirmation:
Your submission has been received! You’ll receive an email as soon as early access is available.

Please assign me this issue. I will work on it ASAP.
Thank you!

**Comment by Vinay-Khanagavi** [comment]
Contact form in the landing page
