### ISSUE TITLE
Feature Request: Theme Toggle Button

### ISSUE THREAD

**Issue by Shalini22-ui** [Vinay-Khanagavi/Cyberbear.github.io#15]
I would like to propose the addition of a theme **toggle button** on top of the home page to allow users to switch between dark and light themes based on their preference. This feature will enhance user experience by providing the flexibility to choose a theme that best suits individual needs or preferences.

![image](https://github.com/user-attachments/assets/882e87b7-46ca-45ff-ba44-aef901f85c32)
Please assign me this issue with labels gssoc -ext, hacktoberfest-accepted and appropriate level

**Comment by Vinay-Khanagavi** [comment]
Currently wee planned to keep only black theme.. you can work with some other issues, thank you
