### ISSUE TITLE
website dosen't have scroll to top button !

### ISSUE THREAD

**Issue by 2004pra** [Vinay-Khanagavi/Cyberbear.github.io#152]
please allow  me to provide scroll to top button for all the pages of this website
assign me this issue under gssoc extd 24 , hacktoberfest
and please make it level 3 as i am working over all the pages of the website please !
@Vinay-Khanagavi

**Comment by Vinay-Khanagavi** [comment]
We're not in need of that at the moment. Feel free to explore other topics or create new ones. For more guidance, consider exploring the main project or joining our Discord server.
