### ISSUE TITLE
Add a Visitor Counter feature ✨

### ISSUE THREAD

**Issue by Subhajit-2023-44** [Vinay-Khanagavi/Cyberbear.github.io#160]
I want to add a Visitor Counter feature properly.

PA please assign me this task.

![Screenshot 2024-11-01 214415](https://github.com/user-attachments/assets/12a81a7a-87f5-4b9b-afa0-c1c72d9fa11c)

**Comment by Subhajit-2023-44** [comment]
@Vinay-Khanagavi

**Comment by Vinay-Khanagavi** [comment]
Sorry we don't want that. Feel free to explore other topics or create new ones. For more guidance, consider exploring the main project or joining our Discord server.
