### ISSUE TITLE
Add a pop up dialog box for subscribing to newsletter ✨✨

### ISSUE THREAD

**Issue by Subhajit-2023-44** [Vinay-Khanagavi/Cyberbear.github.io#163]
I want to add a pop up dialog box for subscribing to newsletter..

PA please assign me for this task..

**Comment by Subhajit-2023-44** [comment]
@Vinay-Khanagavi sir please assign me

**Comment by Vinay-Khanagavi** [comment]
We're not in need of that at the moment. Feel free to explore other topics or create new ones. For more guidance, consider exploring the main project or joining our Discord server.
