### ISSUE TITLE
Changing Font to give better look

### ISSUE THREAD

**Issue by ragini-gp** [Vinay-Khanagavi/Cyberbear.github.io#17]
Changing the font will give the page better look

Current
![image](https://github.com/user-attachments/assets/d29df721-dbb9-4b16-81a1-846787fb41a2)

Proposed
![image](https://github.com/user-attachments/assets/978df109-941e-4d30-8372-76cd6a0ba57c)

please assign me this issue under labels- gssoc-ext, hacktoberfest-accepted, and level

**Comment by Vinay-Khanagavi** [comment]
We are planning to remove that big title soo that's not needed. You can work on some other issues or might suggest some better fronts or correcting the formatting. Thank you
