### ISSUE TITLE
User Experience Enhancements | Smooth Scrolling Addition of BackToTop Button | Customisation of Side Scrollbar (Theme Matched)

### ISSUE THREAD

**Issue by Shariq2003** [Vinay-Khanagavi/Cyberbear.github.io#21]
These are the Features that I will going to implement :-

1. Smooth Scrolling Addition of BackToTop Button.
2. Customisation of Side Scrollbar that will match with the Theme of the website.

https://github.com/user-attachments/assets/6f1db270-d09a-49e2-868e-96b432c9882c

**Comment by Vinay-Khanagavi** [comment]
Can you rather work on making the design responsive in mobile

**Comment by Shariq2003** [comment]
Yah can also work on that

**Comment by Vinay-Khanagavi** [comment]
Sure you can work on this issue, if the changes are good I'll accept the PR

**Comment by Shariq2003** [comment]
> Sure you can work on this issue, if the changes are good I'll accept the PR

okay sir

**Comment by Shariq2003** [comment]
@Vinay-Khanagavi sir, you have added the label "invalid" in my PR
