### ISSUE TITLE
User Experience Enhancements | Addition of ProgressBar That Will showcases the Remaining Depth of the Webpage during Scrolling

### ISSUE THREAD

**Issue by Shariq2003** [Vinay-Khanagavi/Cyberbear.github.io#22]
Addition of ProgressBar That Will showcases the Remaining Depth of the Webpage during Scrolling

Just like in the GSSOC Website
 
![image](https://github.com/user-attachments/assets/92c3b351-dbb1-49ce-a848-78023a99f0a8)

Look at the top of page, an orange line

**Comment by Shariq2003** [comment]
@B1N4RY-P4R45173 please assign this to me.

**Comment by Vinay-Khanagavi** [comment]
Sorry after discussion we thought of not having this feature thanks for opening issues.
