### ISSUE TITLE
Mouse Cursor Trail Effect

### ISSUE THREAD

**Issue by Priyanshi0112** [Vinay-Khanagavi/Cyberbear.github.io#24]
The mouse cursor trail effect offers several benefits:

1. Improved Visibility: Makes the cursor easier to spot, especially on busy screens.
2. Enhanced Accessibility: Helps users with visual impairments keep track of the cursor.
3. Aesthetic Appeal: Adds a stylish, engaging touch to websites or apps, enhancing user experience.
4. Action Awareness: Useful in presentations or tutorials to highlight cursor movements.

Please assign this issue to me under GSSoC and Hacktoberfest

Thank you

**Comment by Vinay-Khanagavi** [comment]
do PR if it looks good then I'll merge it

**Comment by Priyanshi0112** [comment]
I would like to confirm whether the effect currently used on the homepage is appropriate for other pages as well, or if it works best as a unique feature of the homepage. Should I consider applying this effect site-wide, or does it serve its purpose better as a distinct design element for the homepage only?
https://github.com/user-attachments/assets/8d336296-3fea-41c2-a1a5-f909cb6ef46d

**Comment by Priyanshi0112** [comment]
I would like to confirm whether the effect currently used on the homepage is appropriate for other pages as well, or if it works best as a unique feature of the homepage. Should I consider applying this effect site-wide, or does it serve its purpose better as a distinct design element for the homepage only?
https://github.com/user-attachments/assets/8d336296-3fea-41c2-a1a5-f909cb6ef46d

**Comment by B1N4RY-P4R45173** [comment]
Hey @Priyanshi0112 we have some ideas regarding this. Please wait for a day and we will get back to you

**Comment by Priyanshi0112** [comment]
okay @B1N4RY-P4R45173

**Comment by ishivansmishra** [comment]
@Vinay-Khanagavi  Please assign me the issue

**Comment by Vinay-Khanagavi** [comment]
@Priyanshi0112  Thanks for the contribution but after discussion with this issues we made decision of not having the the cursor effect
