### ISSUE TITLE
Readme updation

### ISSUE THREAD

**Issue by eshalshaikh07** [Vinay-Khanagavi/Cyberbear.github.io#28]
I’ve been diving into your project, and WOW – it’s awesome! 🌟 While going through the README, I thought it could shine even more with a bit of visual enhancement. 🎨✨

Here’s what I can help with:

📸 Adding relevant images or screenshots to clarify steps
🎞️ Including GIFs to demonstrate features in action
🛠️ Enhancing sections with emojis for better readability and fun

I’d love to contribute by giving the README a refreshing update! Let me know if this is something you'd be interested in or if you have any specific ideas in mind. Looking forward to your thoughts!

Thanks a bunch! 🙏

**Comment by B1N4RY-P4R45173** [comment]
### Hey @eshalshaikh07 👋

Thanks a ton for the PR! 🙌  

We've been thinking about making some improvements, and your contribution is perfectly timed. 🎯 Could you help us by giving the `README.md` a little refresh? Specifically, we’d like to:  

1. **Move the contributing guidelines** into a new `CONTRIBUTING.md` file to keep things organized.  
2. **Add a link to our upcoming Discord server** so contributors can easily connect and collaborate.

**Comment by eshalshaikh07** [comment]
> ### Hey @eshalshaikh07 👋
> Thanks a ton for the PR! 🙌
> 
> We've been thinking about making some improvements, and your contribution is perfectly timed. 🎯 Could you help us by giving the `README.md` a little refresh? Specifically, we’d like to:
> 
> 1. **Move the contributing guidelines** into a new `CONTRIBUTING.md` file to keep things organized.
> 2. **Add a link to our upcoming Discord server** so contributors can easily connect and collaborate.

Hey!! greattt I,ll do changes as mentioned along with adding animations and gif will update you!!

**Comment by Vinay-Khanagavi** [comment]
@eshalshaikh07  
https://discord.gg/wFWtpVmB       Join this discord server and send the readme file soon or this issue will be closed

**Comment by B1N4RY-P4R45173** [comment]
Hello @eshalshaikh07 
We need to act quick on this, as we plan on bringing more changes and without first completing this, we cannot proceed further. Please join the discord server and open a forum in the issues channel and I will help you. This is urgent. Thankyou

**Comment by B1N4RY-P4R45173** [comment]
Hey @eshalshaikh07 it has been 2 days since your last comment.  And I don't see a pr from you yet. If you fail to submit a pr within the next 12 hours we will have to assign this someone else.

**Comment by anchalchaturvedi08** [comment]
can I work on this issue?

**Comment by Vinay-Khanagavi** [comment]
Sure @anchalchaturvedi08
