### ISSUE TITLE
Automated Greeting Workflow

### ISSUE THREAD

**Issue by archanasingh11** [Vinay-Khanagavi/Cyberbear.github.io#29]
## Description

I propose the implementation of a GitHub Actions workflow named **"Greetings"** to automatically greet users when they open new issues or pull requests. This will enhance communication with contributors and provide immediate acknowledgment of their submissions.

### Key Features:
- **Automatic Greetings**: 
  - **For Issues**: When a user opens an issue, they will receive an automatic message like:  
    "👋 Thank you for raising an issue! We appreciate your effort in helping us improve. Our team will review it shortly. Stay tuned!"
  - **For Pull Requests**: When a pull request is submitted, the user will receive a message such as:  
    "🎉 Thank you for your contribution! Your pull request has been submitted successfully. A maintainer will review it as soon as possible. We appreciate your support in making this project better."

### Benefits:
- **Improved Communication**: Immediate, automated acknowledgment for contributors helps improve transparency and engagement.
- **Contributor Experience**: Contributors feel valued and informed about the next steps as soon as they submit their issue or pull request.
- **Time Efficiency**: Maintainers save time on manual acknowledgments, allowing more focus on reviewing contributions.

Implementing this feature will enhance contributor experience and streamline communication for the project.

Please @Vinay-Khanagavi assignme this task with labels "gssoc-ext" , "hacktoberfest-accepted" and "level3"

**Comment by B1N4RY-P4R45173** [comment]
### Hello @archanasingh11 

Thanks for the detailed proposal! 🙌  

We’d love to see a **GitHub Actions "Greetings" workflow** added to the project.

### **Important Note**  
The **task level** will depend on **how stable and dynamic** the workflow is:
- **Basic Setup**: Simple greeting for issues and PRs.
- **Dynamic Setup**: Conditional greetings based on labels (like "gssoc-ext" or "hacktoberfest-accepted") or event types for more customization.

Feel free to ask if you need any help or guidance along the way. We look forward to your contribution! 😊

**Comment by archanasingh11** [comment]
okay sure
But dont froeget to assign me the labels which will help to consider my participation in gssoc-ext
