### ISSUE TITLE
Add Transition Effect to CyberBear for Improved UI Performance

### ISSUE THREAD

**Issue by ansiace** [Vinay-Khanagavi/Cyberbear.github.io#31]
The "CyberBear" element currently lacks a transition effect, which impacts the smoothness and interactivity of the UI. Adding a transition effect will create a more dynamic and visually appealing user experience, aligning with the overall design of the site.

### Current Behavior
- The "CyberBear" element does not have any transition effect, resulting in a static and less engaging interaction for the user.

### Expected Behavior
- The "CyberBear" element should have a transition effect on hover or interaction, enhancing user experience and making the UI feel more interactive and fluid.

![image](https://github.com/user-attachments/assets/e3ae7b67-a1c0-4717-a26e-78949677a85d)

**Comment by B1N4RY-P4R45173** [comment]
@ansiace  Thanks for bringing this issue under our notice.

As of now we are unable to process if your suggested looks good or not. Can you please add the changes that you think will make the UI better. If we like well merge it.

**Comment by B1N4RY-P4R45173** [comment]
### Hello @ansiace  
Please join our discord server to discuss about this issue. We might have to close this issue if you don't respond within 24hrs.

**Comment by ansiace** [comment]
i want to add transition-transform in that issue.  but it seems the page isn't loading properly right now.

**Comment by B1N4RY-P4R45173** [comment]
It seems fine for me. Please check once again and let us know if you face any issues.
https://vinay-khanagavi.github.io/Cyberbear.github.io/

Also join our discord server for all the updates. 
https://discord.gg/YFWmkphf

**Comment by ansiace** [comment]
Thank you @B1N4RY-P4R45173  for the update! I’ve checked the link and everything seems to be working perfectly now in Chrome. I really appreciate your prompt response and resolution of the issue. I'll go ahead and consider this issue resolved
