### ISSUE TITLE
bug: play button is not working 

### ISSUE THREAD

**Issue by Aditya90456** [Vinay-Khanagavi/Cyberbear.github.io#32]
play button is not working 
![127 0 0 1_5500_homepage html and 8 more pages - Personal 2 - Microsoft​ Edge Beta 10_16_2024 2_09_48 PM](https://github.com/user-attachments/assets/87297359-b288-4961-a85a-a889f76c8ec0)

**Comment by Vinay-Khanagavi** [comment]
check again it's working  https://vinay-khanagavi.github.io/Cyberbear.github.io/

**Comment by B1N4RY-P4R45173** [comment]
The problem is with level3 and 4
