### ISSUE TITLE
Enhancement of hint.html page

### ISSUE THREAD

**Issue by Aditya90456** [Vinay-Khanagavi/Cyberbear.github.io#34]
![127 0 0 1_5500_homepage html and 8 more pages - Personal 2 - Microsoft​ Edge Beta 10_16_2024 2_49_21 PM](https://github.com/user-attachments/assets/05000cb8-b75b-4fbb-afda-3e79ec8cb516)

Enhancement of hint.html page

**Comment by B1N4RY-P4R45173** [comment]
@Aditya90456 We will be closing this issue as we didn't get an appropriate pr. You can create a new issue when you have a better design in mind.
