### ISSUE TITLE
Remove duplicate and old files and fix the structure of codebase

### ISSUE THREAD

**Issue by B1N4RY-P4R45173** [Vinay-Khanagavi/Cyberbear.github.io#37]
While building this project, we created several similar code versions to test which one looked and performed better. Now that we have a proper interface in place, I believe it's time to remove duplicate and unnecessary files. Additionally, some files need to be modified, as the connectivity to subsequent levels is broken on certain pages

## Example1:
![{AE2644AE-64DF-4F94-BC0A-88F192592520}](https://github.com/user-attachments/assets/804c1bca-f516-4700-b571-f04b88d9302f)
## Example2:
![{2EECFC5D-8650-4961-92A6-A83D1CBA431C}](https://github.com/user-attachments/assets/8d16f32d-e56d-41ae-a880-2724a9c9f95f)
### As you can see in the above image it points to a dead link which when opened, results in

![{FDE7150E-90AB-47DE-A523-1E6B0D790ABC}](https://github.com/user-attachments/assets/c3f88c24-3f1e-47ca-bf1d-c1e6c6c07459)

**Comment by 4bh7n4v** [comment]
Please Assign this to me @Vinay-Khanagavi

**Comment by B1N4RY-P4R45173** [comment]
Sure Please join our discord server https://discord.gg/YFWmkphf for more updates
