### ISSUE TITLE
Add visuals to indicate whether the weather sound icon is turned on or off in the homepage

### ISSUE THREAD

**Issue by B1N4RY-P4R45173** [Vinay-Khanagavi/Cyberbear.github.io#39]
### Current homepage design:

![{4729C084-4D46-4EFA-BA90-5DDA08CC554E}](https://github.com/user-attachments/assets/d55112b9-b576-42f2-a773-3bb3bd53e038)

### Expected design
![Untitled design](https://github.com/user-attachments/assets/805cb196-5804-42f4-ada6-b522f65231df)

### Look at the top right (music icon)

**Comment by hemanth-kumar-1** [comment]
hlo @B1N4RY-P4R45173 , please assign this to me

**Comment by B1N4RY-P4R45173** [comment]
okay, please join our discord server for all the updates. https://discord.gg/YFWmkphf

**Comment by Talha-ai** [comment]
Hi, I am interested in implementing this feature.

**Comment by B1N4RY-P4R45173** [comment]
### Hello @Talha-ai 

Thanks for showing your interest in this issue. But unfortunately this has already been assigned to @hemanth-kumar-1. You can contribute to other issues. And if we don't get a pr from @hemanth-kumar-1 then we will reassign this to you.

**Comment by ishivansmishra** [comment]
please assign me this issue @Vinay-Khanagavi I will fixed it soom

**Comment by hemanth-kumar-1** [comment]
##Hello @B1N4RY-P4R45173 ,
I will send a pr soon
