### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by aditya-githb** [Vinay-Khanagavi/Cyberbear.github.io#4]
add tooltip in the the icon of index page because it is harder to understand what the icon does
![image](https://github.com/user-attachments/assets/7c9932a6-beb6-491a-a6fa-7189af1b53fe)

**Comment by Vinay-Khanagavi** [comment]
Yes that's understandable

**Comment by Vinay-Khanagavi** [comment]
Please add tooltips to all icons on the index page to improve clarity. When hovered, the tooltip should display a brief description of the icon’s function. Additionally, I’d appreciate menu bar suggestions to enhance the current design, while keeping it intuitive and user-friendly. Thanks!

**Comment by aditya-githb** [comment]
> Please add tooltips to all icons on the index page to improve clarity. When hovered, the tooltip should display a brief description of the icon’s function. Additionally, I’d appreciate menu bar suggestions to enhance the current design, while keeping it intuitive and user-friendly. Thanks!

sure
