### ISSUE TITLE
Contribution.md Creation

### ISSUE THREAD

**Issue by milansamuel609** [Vinay-Khanagavi/Cyberbear.github.io#42]
I just wanted to ask that can I create the contribution.md file which can allow the contributors know in which ways they can contribute and also what rules and code of conduct all they have to follow and also some other section. Please can you assign me this issue.

**Comment by B1N4RY-P4R45173** [comment]
### Hello @milansamuel609
Thanks for raising this issue. We acknowledge that there is a need for `CONTRIBUTIONS.md` but it will be covered in #28
So as of now we don't need a pr on this.

Thankyou
