### ISSUE TITLE
enhance readme

### ISSUE THREAD

**Issue by Aditijainnn** [Vinay-Khanagavi/Cyberbear.github.io#43]
In readme also add contributors profile in readme and go to top toggle and much assign this to me under gssoc ext and hacktoberfest

**Comment by B1N4RY-P4R45173** [comment]
@Vinay-Khanagavi Do we need this? Obviously everyone can see the contributors at the home page adding another file for that should be unnecessary

**Comment by B1N4RY-P4R45173** [comment]
@Aditijainnn please join our discord server to discuss this further https://discord.gg/YFWmkphf

**Comment by Vinay-Khanagavi** [comment]
No we don't
