### ISSUE TITLE
Add contact links in footer

### ISSUE THREAD

**Issue by Aditijainnn** [Vinay-Khanagavi/Cyberbear.github.io#44]
![image](https://github.com/user-attachments/assets/02d6c81e-3771-4f9f-acb5-b7cbf55a710b)
in footer adding github linkdin and gmail incon with links
assign this to me under gssoc ext and hacktoberfest

**Comment by Vinay-Khanagavi** [comment]
Currently we don't want to any change in the UI of landing page, go through our main project https://vinay-khanagavi.github.io/Cyberbear.github.io/

Join the discord server for guidance: https://discord.gg/wFWtpVmB
