### ISSUE TITLE
Bug in Level4 where same option could be clicked more than once

### ISSUE THREAD

**Issue by B1N4RY-P4R45173** [Vinay-Khanagavi/Cyberbear.github.io#50]
### Check this recording

https://github.com/user-attachments/assets/4d61bb16-1b90-4477-994f-b479a7586ef1

**Comment by Crimson-Typhoon-147** [comment]
Hey @B1N4RY-P4R45173 I can work on this. please assign this issue to me.

**Comment by Crimson-Typhoon-147** [comment]
Thank you so much for assigning the issue.

**Comment by B1N4RY-P4R45173** [comment]
Hello @Crimson-Typhoon-147 are you still working on this?

**Comment by Crimson-Typhoon-147** [comment]
Yes working on it. I'll try to complete it by tonight.


> Hello @Crimson-Typhoon-147 are you still working on this?

**Comment by Crimson-Typhoon-147** [comment]
Hey @B1N4RY-P4R45173 Have made a pr fixing this. Please review and merge it.

https://github.com/Vinay-Khanagavi/Cyberbear.github.io/pull/87
