### ISSUE TITLE
Updation of DEMO Pics

### ISSUE THREAD

**Issue by neeru24** [Vinay-Khanagavi/Cyberbear.github.io#55]
Hi, In the readme, these pics should be replaced with the screenshots of the current website.

These pics are old and adding new ones that are current would give users a better idea and overview of the project.

Would like to change these. Kindly assign me this issue.

![image](https://github.com/user-attachments/assets/4e6aeaf0-2fb6-4dbd-b47f-5951c4ee1359)

**Comment by B1N4RY-P4R45173** [comment]
Hello @neeru24,

Thank you for bringing this up! I've been considering this for a while, and while updating the demo pictures is a valid point, it may not provide long-term value. Given the high volume of incoming changes, the UI will evolve frequently, making such updates quickly outdated.

It might be more practical to revisit this task at a later stage.
