### ISSUE TITLE
Feat:adding a new page to display all contributors✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [Vinay-Khanagavi/Cyberbear.github.io#57]
I want to add a page to showcase all the contributors of this website. @Vinay-Khanagavi can you please assign me this issue.

**Comment by Vinay-Khanagavi** [comment]
@T-Rahul-prabhu-38  I think we currently don't want that but you could work some other suggestion issues which we added in our discord server 

https://discord.gg/wFWtpVmB
