### ISSUE TITLE
Adding multi language support system✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [Vinay-Khanagavi/Cyberbear.github.io#58]
I want to add multi language support system to the website which can help us understand in their native language.
@Vinay-Khanagavi can you assign me this issue.

**Comment by Vinay-Khanagavi** [comment]
I don't think wee need, but you could help us on making better leaderboard design let me know if you are interested @T-Rahul-prabhu-38  

![image](https://github.com/user-attachments/assets/b484a494-f3e3-4807-aa8f-da823cb3bb21)

**Comment by T-Rahul-prabhu-38** [comment]
i can try

**Comment by Vinay-Khanagavi** [comment]
Whenever a user completes first level there's a pop asking there name to save that name which they should show up in leaderboard and the design you can take reference from any game web and also if you want any guidance then you can share your questions, designs in this discussion

https://github.com/Vinay-Khanagavi/Cyberbear.github.io/discussions/16

**Comment by T-Rahul-prabhu-38** [comment]
sure ill give it a try, whats the tech stack

**Comment by Vinay-Khanagavi** [comment]
Currently you can work on html, CSS and JavaScript

**Comment by Vinay-Khanagavi** [comment]
Need to add state management, calculate points of users and store it with user name and points, please join the discord server and keep sharing the progress, Thank you

**Comment by B1N4RY-P4R45173** [comment]
@T-Rahul-prabhu-38  Please raise a new issue if you want to work on any other issue. Multi Language support is available with google translate.
