### ISSUE TITLE
Hover efffect on img tag and box shadow

### ISSUE THREAD

**Issue by rohir1132yadav** [Vinay-Khanagavi/Cyberbear.github.io#59]
i want to apply Hover efffect on img tag and box shadow

**Comment by rohir1132yadav** [comment]
i want to work on this issue #59 . please assign me under gssoc-ext and hactoberfest

**Comment by Vinay-Khanagavi** [comment]
@rohir1132yadav  Please share some of your work which is similar to this issue if that looks good you can work on this

**Comment by rohir1132yadav** [comment]
https://github.com/user-attachments/assets/9a5dca30-a51c-4ced-ae26-a70a075e3857

![WhatsApp Image 2024-10-18 at 00 23 13_691684a2](https://github.com/user-attachments/assets/74e66d0f-1f30-4053-9106-24b199d030f8)

**Comment by Vinay-Khanagavi** [comment]
@rohir1132yadav  I think we currently don't want that but **you could work some other suggestion issues** which we added in our discord server

https://discord.gg/wFWtpVmB
