### ISSUE TITLE
User Experience Improvement: Introduce a "Scroll to Top" Button

### ISSUE THREAD

**Issue by ragini-gp** [Vinay-Khanagavi/Cyberbear.github.io#6]
I would like to add a "Scroll to Top" button for this application. This feature will improve user experience by allowing users to quickly navigate back to the top of the page, irrespective of their current scroll position.
![image](https://github.com/user-attachments/assets/3790da25-cd5c-4c00-bd51-d4d4dcd54fd3)

Please assign me this issue, with labels- hacktoberfest-accepted, gssoc-ext and appropriate level

**Comment by Vinay-Khanagavi** [comment]
Sure also organize the project files by moving all . css files to a css/ folder, and group the index-level HTML files into a levels/ directory. Also, place media files like back.mp3 into a media/ or audio/ folder. 

Ensure all paths are updated and test the project to verify everything works. Once done, open a pull request for review.

**Comment by ragini-gp** [comment]
Sure, will do
