### ISSUE TITLE
missing CONTRIBUTING.md

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [Vinay-Khanagavi/Cyberbear.github.io#61]
## Description
This pull request addresses the issue of the missing `CONTRIBUTING.md` file, which is essential to help new contributors understand how to contribute to the project effectively. It outlines contribution guidelines, community communication, and additional resources to ensure a smooth contribution process.
## Key Changes

- Added a `CONTRIBUTING.md` file to the project.
- The file includes:
  - Clear contribution guidelines to help new contributors.
  - Best practices for submitting issues and pull requests.
  - Community communication channels.
  - Additional resources for contributors to learn more about the project.

## Screenshot
![missing_contributing](https://github.com/user-attachments/assets/a24b321b-7bb7-4c1e-9f1e-838fd4904cef)

**Comment by B1N4RY-P4R45173** [comment]
Thanks @biswajit-sarkar-007 for bringing up the issue, but unfortunately someone is already working on the same. see #28
