### ISSUE TITLE
Navbar ui

### ISSUE THREAD

**Issue by Aditya90456** [Vinay-Khanagavi/Cyberbear.github.io#67]
![Swasthya Point and 8 more pages - Personal 2 - Microsoft​ Edge Beta 10_18_2024 9_47_05 AM](https://github.com/user-attachments/assets/fbee7da8-af40-43a8-9847-436bee34c0e5)

**Comment by Vinay-Khanagavi** [comment]
Sorry currently we are not planning to change anything form the landing page please focus on main project
