### ISSUE TITLE
Fixing level 2 page

### ISSUE THREAD

**Issue by Talha-ai** [Vinay-Khanagavi/Cyberbear.github.io#69]
Implementing the below features in page 2 as done same in page 1.

1) Multiple retires in the questions page.
2) Explanation when user chooses wrong answer.
3) Redirect to explanation page if user loses.
4) Amazon kid friendly voucher card text.

**Comment by B1N4RY-P4R45173** [comment]
As discussed in Discord please just fix one level first. And according to the level you choose, update the title
