### ISSUE TITLE
Level 1/2/3 Interactive Elements: User Experience

### ISSUE THREAD

**Issue by aditichhawacharia** [Vinay-Khanagavi/Cyberbear.github.io#7]
Since CyberBear is aimed towards kids, the website (videos and lessons) should be as kid friendly as possible. 

I think fonts, text and vocab should be edited to be more kid friendly.
![Screenshot 2024-10-13 235850](https://github.com/user-attachments/assets/471982e3-b60b-4e52-9c30-0f148e4650dd)

This is another example - Is not user friendly especially towards kids. 
![Screenshot 2024-10-14 000403](https://github.com/user-attachments/assets/4e54befe-6c4d-4c46-96ba-da0361ab49ae)
![example2](https://github.com/user-attachments/assets/a9b03eb9-5170-45db-8f8d-ec10aa416f6e)
There should be a clear mention of it being a game or a example of what could happen as kids may not understand that this is part of the lessons (they might actually think this is a virus).

Videos like these that are embedded in the lessons have bad framing, take up the whole screen, are hard to navigate, skip and pause + skip section is too far bottom for a kid to take notice. There is also unclear text or explanations for what the video is. I think the video should be put in the center, framed, a bit smaller with text explaining it, clear pause, fast forward, speed and skip buttons.
![video](https://github.com/user-attachments/assets/cea75b2a-6654-436f-8a71-82184d5f2e8f)

**Comment by Jasmeetkaur-13** [comment]
I'm ready to enhance the user experience with these features.

**Comment by B1N4RY-P4R45173** [comment]
Hello @Jasmeetkaur-13 How is the progress?

**Comment by B1N4RY-P4R45173** [comment]
Since there has been no response from your side for two days, I will be unassigning you. But feel free to ask us once again to assign you

**Comment by B1N4RY-P4R45173** [comment]
This will be covered in 3 separate issues
