### ISSUE TITLE
Fix: Consistency of design of home page for smaller screen

### ISSUE THREAD

**Issue by vaibhav-yerkar** [Vinay-Khanagavi/Cyberbear.github.io#72]
issue : For smaller screens , for home page, the design to represent the levels are inconsistent ,i.e, 
 - For level 1 : description, level-1 (title), play button, gif
 - For level 2: gif, title, play button , description
 - For level 3: description, title, play button, gif
 - For level 4: gif, title, play button, description
 

Video : 
https://github.com/user-attachments/assets/8259a5e8-2cf3-4cf2-91b7-246243fdf8c2

Suggested: 
- Refactoring index.html code and the styling properties to make the UI better and consistent designing

**Comment by Vinay-Khanagavi** [comment]
Sure we would like that please do PR as soon as possible,
we might tell you to change the position but still you can try out first and share the design in #16  Discussion
@vaibhav-yerkar

**Comment by B1N4RY-P4R45173** [comment]
@vaibhav-yerkar please wait till I confirm. I think someone is already working on a similar issue.

**Comment by vaibhav-yerkar** [comment]
@B1N4RY-P4R45173  Sure

**Comment by B1N4RY-P4R45173** [comment]
@vaibhav-yerkar There is already a person assigned to work on a similar issue for the home page. If you want you could design the responsive pages for all the levels. So the way I would like is all the levels in separate prs. Or level1 and 2 in one pr and level 3 and level 4 in another pr.

**Comment by Dhruvi-tech** [comment]
i want to work on level one anything that could be assigned

**Comment by Vinay-Khanagavi** [comment]
@Dhruvi-tech 

**Add a silent music which plays after the demo video is over and it plays until the first level quiz is completed!!
create an different issue for this if you want to work, thanks you.**

**Comment by vaibhav-yerkar** [comment]
Should I raise different issue for each PR @B1N4RY-P4R45173

**Comment by B1N4RY-P4R45173** [comment]
yes
