### ISSUE TITLE
Add Back to home page button on other button

### ISSUE THREAD

**Issue by Sudhanshu248** [Vinay-Khanagavi/Cyberbear.github.io#74]
There is no button of back to home page on other pages. So it is difficult for user to come on home page from other pages.

![Screenshot 2024-10-18 195658](https://github.com/user-attachments/assets/7b382eda-d5b1-4f5c-bc6b-ac6b1662690c)

![Screenshot 2024-10-18 195721](https://github.com/user-attachments/assets/7b20d222-14dc-4f59-aba1-f863c030edf3)

**Comment by Sudhanshu248** [comment]
@Vinay-Khanagavi    Kindly assign me the issue under the label of gssoc-ext, hacktoberfest'24, hacktoberfest-accepted, level-2.

**Comment by B1N4RY-P4R45173** [comment]
@Sudhanshu248 What exactly do u want to add here?? a button that redirects to home page from any other page or do you have something different in mind?

**Comment by Sudhanshu248** [comment]
@B1N4RY-P4R45173                A button that redirects to home page from any other page.

**Comment by B1N4RY-P4R45173** [comment]
Thanks for confirming @Sudhanshu248. But as of now we don't see any requirement for this
