### ISSUE TITLE
Add contributing.md file

### ISSUE THREAD

**Issue by Nikhil0-3** [Vinay-Khanagavi/Cyberbear.github.io#76]
Without a CONTRIBUTING.md file, potential contributors may not know how to contribute effectively. This could lead to inconsistencies in contributions and confusion among contributors.
Missing Code of Conduct:

**Comment by B1N4RY-P4R45173** [comment]
Thankyou for raising the issues @Nikhil0-3 but this issues already exists, refer #28 and #47
