### ISSUE TITLE
adding Hacktoberfest  & gssoc-ext fest logo in the readme 

### ISSUE THREAD

**Issue by REHAN-18** [Vinay-Khanagavi/Cyberbear.github.io#77]
adding the logo will enhance  the readme.. update the readme.

**Comment by Vinay-Khanagavi** [comment]
@REHAN-18  can you share some examples of how that looks

**Comment by REHAN-18** [comment]
@Vinay-Khanagavi yes sure!
<img width="708" alt="Screenshot 2024-10-18 at 8 47 49 PM" src="https://github.com/user-attachments/assets/96621c23-9d18-4ce2-847c-efbc58bb01fd">
<img width="989" alt="Screenshot 2024-10-18 at 11 57 18 PM" src="https://github.com/user-attachments/assets/5e6dd391-c87c-4040-9715-5a25a840d9c4">

**Comment by REHAN-18** [comment]
@Vinay-Khanagavi like this !!

**Comment by Vinay-Khanagavi** [comment]
Sorry I don't think we need it, you can work on some other issues
