### ISSUE TITLE
Level 1: Amazon Voucher Interactive Elements + Questions

### ISSUE THREAD

**Issue by aditichhawacharia** [Vinay-Khanagavi/Cyberbear.github.io#8]
![Screenshot 2024-10-14 000759](https://github.com/user-attachments/assets/942ec380-0e15-4ad8-8dfc-ba971bd0d2bf)
Again, should make this kid friendly through better text and fonts + MENTION AT THE TOP, that this is part of the game and lesson and is not actually serious.

![questions](https://github.com/user-attachments/assets/95939214-c545-456b-a503-78fac7af15f3)
Questions should be worded better. **If a question is wrong, there should be an explanation for the correct one, plus multiple retries.**

If the user gets the questions wrong, instead of it putting the "Mission Failed" Page, it should show the explanation.
![understanding phishing attacks](https://github.com/user-attachments/assets/ec5fbd50-91fc-4371-b049-234a72892821)

![Level2](https://github.com/user-attachments/assets/031ef0f5-6a41-440e-956c-6efabf85d5a0)
Level 2 is a broken link.

**Comment by B1N4RY-P4R45173** [comment]
Level2 link has been however Level3 and Level4 are still broken and will be fixed in #40

**Comment by Talha-ai** [comment]
I am interested in fixing and implementing the said features. Please assign it to me.
