### ISSUE TITLE
Addign more Questions to the Game (LEVEL 1)

### ISSUE THREAD

**Issue by tejasam571** [Vinay-Khanagavi/Cyberbear.github.io#81]
For the **CyberBear Project**, we designed an interactive game aimed at raising awareness about cybersecurity. In this game, players navigate a bear character through various levels, answering cybersecurity-related questions that appear in the game field. The questions cover topics such as safe internet practices, password security, phishing, and malware. By answering correctly, players can advance through the levels, reinforcing their knowledge of cybersecurity in a fun and engaging way. The project promotes awareness while ensuring an enjoyable and educational experience for all players.

![image](https://github.com/user-attachments/assets/51f169e3-237a-4f11-bed5-ee06971c5959)

**Comment by Vinay-Khanagavi** [comment]
I think it will get boring if you add more then 2 questions

 **We are thinking to have some different approach throughout the project  not just quizzes this project is for kids, scenario and character development should be main priority or making it more engaging with some other games**
