### ISSUE TITLE
Fixing the height of the translate button

### ISSUE THREAD

**Issue by KrishPatel1205** [Vinay-Khanagavi/Cyberbear.github.io#84]
## Description
The issue here is that the translate button is in the middle of the page and makes the page look distracting and visually displeasing. it should be somewhere lover in the corner so that it doesn't cause a distraction to the user. It can be seen below as I have highlighted the issue using a red box.

## Screenshot
<img width="1912" alt="Screenshot 2024-10-19 at 3 59 12 PM" src="https://github.com/user-attachments/assets/766cf0af-127c-499e-a507-45c4b54bf890">

**Comment by KrishPatel1205** [comment]
@B1N4RY-P4R45173 Please check this out

**Comment by Vinay-Khanagavi** [comment]
Already resolved, please find some issues which are needed
