### ISSUE TITLE
New Feature to Skip Levels once the Level has started

### ISSUE THREAD

**Issue by SagarSharma2809** [Vinay-Khanagavi/Cyberbear.github.io#92]
Amazing website! I already completed level 1 when I first visited, but opening it again after sometime, I started the level 1 again to show someone how cool this website is. 

But, since I already had completed level 1 in past, I just wanted to skip the level and move onto level 2. There was no skip button.

I can add a skip button so that user can skip to the end of the level 1. I can add a skip button in the bottom right of the page.

I can work on this new feature if assigned. Thank you! 

![image](https://github.com/user-attachments/assets/5d1e6d49-00a3-4e51-bd36-266db276e7a2)

**Comment by B1N4RY-P4R45173** [comment]
Thanks for the bringing this to our notice @SagarSharma2809.

We do have an option to directly go to the second/third/fourth levels. It just hasn't been properly updated in https://cyberfit-landing-page.web.app/

U can check our alternate website https://vinay-khanagavi.github.io/Cyberbear.github.io/

**Comment by SagarSharma2809** [comment]
is there an option to close the current level or go back to home page directly? I checked both the websites and couldn't find one.

![image](https://github.com/user-attachments/assets/051cd608-b208-4073-86ce-e801c8f5b088)

**Comment by B1N4RY-P4R45173** [comment]
> is there an option to close the current level or go back to home page directly? I checked both the websites and couldn't find one.

Okay I am Sorry I think I misunderstood, your issue. I thought it was about skipping directly to other levels. Ig we can add a home button to all the pages in all the levels. Submit a pr for it
